import Head from 'next/head';
import Image from 'next/image';
import Projects from '../components/Projects';
import Footer from '../components/Footer';
import styles from '../styles/Home.module.css';
import About from '../components/About';
import { motion } from 'framer-motion';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Joshua Coutinho | UX Designer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <motion.div exit={{ opacity: 0 }}>
        <div className='flex flex-col h-auto justify-evenly'>
          <div className='m-auto text-center font-poppins p-28'>
            <h1 className='text-5xl mt-10 mb-5 font-bold'>Hi, I&apos;m Joshua- a UI/UX designer</h1>
            <span className='text-2xl font-light'>Utilizing creativity to create awesome designs with accessiblity in mind</span>
          </div>
          <Projects />
          <Footer />
        </div>
      </motion.div>
    </div>
  );
}
